server:
  port: 8083

spring:
    data:
      mongodb:
        uri: mongodb://localhost:27017
        database: hotel


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9090/eureka